### ISSUE TITLE
Autokey-gtk won't launch – "distribution was not found"

### ISSUE THREAD

**Issue by gazeto** [autokey/autokey#63] opened 2017-01-18 16:13 UTC
Classification: Crash/Hang/Data Loss

Reproducibility: Always

## Summary

Autokey-gtk won't launch, printing "distribution was not found".

## Steps to Reproduce

I simply run autokey-gtk, which usually worked well.

## Actual Results

```
[gazeto@opaque ~]$ autokey-gtk
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'autokey==0.93.7' distribution was not found and is required by the application
[gazeto@opaque ~]$ 

```

## Version

autokey-py3 0.93.9-2

Distro: 4.9.2-1-MANJARO #1 SMP PREEMPT Mon Jan 9 11:19:53 UTC 2017 x86_64 GNU/Linux

**Comment by gazeto** [comment] 2017-01-18 16:27
I had another look at https://aur.archlinux.org/packages/autokey-py3/ and found a solution. Finally 

`sudo pacman -R python-xlib autokey-py3 && sudo pacman -S python-xlib && yaourt -S autokey-py3`

worked, as suggested in AUR. However I also tried different things before (like (re)installing python3-xlib dbus-python)....

**Comment by troxor** [comment] 2017-01-18 17:06
Duplicate of #62, this is an Arch PKGBUILD issue.

**Closed as completed by troxor** 2017-01-18 17:06 UTC
