### ISSUE TITLE
Special characters in "Paste using Keyboard"

### ISSUE THREAD

**Issue by owcz** [autokey/autokey#49] opened 2016-12-11 04:27 UTC
**Setup**
1. New phrase with text "1—2" (an em dash symbol)
2. Set to "Paste using Keyboard" (the default)
3. Set a hotkey (as on Mac, alt+shift+hyphen)

**Actual/Expected**
When I run this, the text will write as "12" as if the em dash was not there. Same if there was nothing besides the em dash in the phrase (nothing would write from the keyboard). The workaround is to Paste using Clipboard, but I imagine this is a bug.

Latest Manjaro 16.10.1, kernel 4.8.9

**Comment by troxor** [comment] 2016-12-11 05:09
Related/duplicate of #29

**Closed as completed by troxor** 2016-12-11 05:09 UTC

**Comment by Lonniebiz** [comment] 2020-11-02 17:08
Related: https://stackoverflow.com/questions/11184300/

**Comment by Lonniebiz** [comment] 2020-11-02 17:52
**Related:** https://stackoverflow.com/questions/11184300/

**Comment by josephj11** [comment] 2020-11-04 04:15
@Lonniebiz Thanks for the link. I added a comment to that question for people who find it in the future.
