### ISSUE TITLE
Qt version does not start when installed from pip

### ISSUE THREAD

**Issue by vvch** [autokey/autokey#414] opened 2020-05-04 18:17 UTC
## Classification:

Crash/Hang/Data Loss

## Reproducibility:

Always

## Version

AutoKey version: 0.95.4

Used GUI (Gtk, Qt, or both): Qt

If the problem is known to be present in more than one version, please list all of those.

Installed via: pip3

Linux Distribution:
Ubuntu 19.10
Qt: 5.12.4
KDE Frameworks: 5.62.0

## Summary

When installed via pip3, Qt interface does not start (but GTK interface can work).
One of the possible reasons: UI icons are installed to `/usr/local/share/icons`, but the program tries to open them from `/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/`

```
> python3 -m autokey.qtui
/usr/local/lib/python3.7/dist-packages/autokey/qtui/common.py:38: UserWarning: Compiled Qt resources file not found. If autokey is launched directly from the source directory, this is expected and harmless. If not, this indicates a failure in the resource compilation.
  warnings.warn(warn_msg)
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 323, sequence_number = 43, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 323, sequence_number = 44, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 323, sequence_number = 45, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 323, sequence_number = 46, major_opcode = 33, minor_opcode = 0
qt.svg: Cannot open file '/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/autokey-status.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/autokey-status.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/autokey-status.svg', because: No such file or directory
```
Message box appears with following error message:
`Fatal error starting AutoKey.`
`<built-in function connectSlotsByName> returned a result with an error set`

## Steps to Reproduce (if applicable)

- `pip3 install autokey`
- `autokey-qt`

## Expected Results

- the program should start

## Actual Results

- error messages

**Comment by josephj11** [comment] 2020-05-04 21:14
I'm not sure, but I think this has been fixed in a newer release. But since you're using Ubuntu, you can install the latest release, 0.95.10, from deb files by following these [instructions](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

**Comment by vvch** [comment] 2020-07-27 11:03
> I'm not sure, but I think this has been fixed in a newer release. But since you're using Ubuntu, you can install the latest release, 0.95.10, from deb files by following these [instructions](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

Thank you, I have installed from .deb. But what is the point to keep knowingly broken old version in pypi, especially when a new fixed version has been available for a long time?

**Comment by josephj11** [comment] 2020-07-27 19:24
I'm not sure about that either, but my best guess is just a shortage developer time and energy. We have one main developer (who has been quiet for a few weeks - and he was quiet last summer, so this may just be vacation time), one who's starting to take on more, and a couple of others who have expressed interest, but I'm not sure if they have contributed yet. That's pretty thin for a project with a lot of fixes and enhancements that need to be addressed.

Send your neighborhood Python experts our way! :)

The original author of the project burned out when he couldn't get any help or donations for several years.

We don't currently have a way to accept donations and no policy as to what we would do with them if we did.

We have had offers from time to time and I think it's something worth discussing. I just do support, but I probably have well over 1000 hours in so far. I haven't logged my time.

**Comment by Elliria** [comment] 2021-11-19 23:09
I'm seeing the same issue in the latest copy of the beta. I'm putting my bug report into the bottom of this one instead of starting a new one.

## Classification:
Crash/Hang/Data Loss

## Reproducibility:
Always

## AutoKey version:
autokey-qt 0.96.0-beta.9

## Used GUI:
Qt

## Installed via:
pip3

## Linux Distribution:
- Kubuntu 20.04 LTS running inside of VirtualBox
- KDE Plasma Version 5.18.5
- KDE Frameworks Version: 5.68.0
- Qt Version: 5.12.8
- Kernel Version: 5.11.0-40-generic
- OS Type: 64-bit
- Memory: 3.2 GiB of RAM
- Processor: 1 x Intel Core i5-8600K CPU @ 3.60 GHz

## Summary:
Same as above. The Qt version of AutoKey cannot be started.

## Steps to reproduce:
1. Install Pip by typing the ```sudo apt install python3-pip``` command into a terminal window.
2. Install AutoKey Beta by typing the ```pip install --user --pre autokey``` command into a terminal window.
3. Try to launch the Qt version of AutoKey by typing the ```~/.local/bin/autokey-qt``` command in a terminal window or typing the ```~/.local/bin/autokey-qt -c``` command in a terminal window.
4. Check the panel for an AutoKey icon.
5. Check for an AutoKey process by typing the ```pgrep -c "autokey"``` command in a terminal window.

## Expected result:
The Qt version of AutoKey should be running and the output of the pgrep command should be 1.

## Actual result:
The Qt version of AutoKey is not running and the output of the pgrep command is 0.

## Notes:
Below is the verbose output produced by attempting to launch autokey-qt with the ```/home/elliria/.local/bin/autokey-qt -c -l``` command for debugging purposes:
```
2021-11-19 16:50:18,651 INFO - autokey.UI_common_functions - Commandline program "visgrep" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "visgrep" exists on your system and is in the $PATH seen by Autokey.
2021-11-19 16:50:18,651 INFO - autokey.UI_common_functions - Commandline program "import" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "import" exists on your system and is in the $PATH seen by Autokey.
2021-11-19 16:50:18,651 INFO - autokey.UI_common_functions - Commandline program "png2pat" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "png2pat" exists on your system and is in the $PATH seen by Autokey.
2021-11-19 16:50:18,651 INFO - autokey.UI_common_functions - Commandline program "xte" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xte" exists on your system and is in the $PATH seen by Autokey.
2021-11-19 16:50:18,652 INFO - autokey.UI_common_functions - Commandline program "xmousepos" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "xmousepos" exists on your system and is in the $PATH seen by Autokey.
Traceback (most recent call last):
  File "/home/elliria/.local/bin/autokey-qt", line 8, in <module>
    sys.exit(Application())
  File "/home/elliria/.local/lib/python3.8/site-packages/autokey/qtapp.py", line 110, in __init__
    missing_reqs = checkRequirements()
  File "/home/elliria/.local/lib/python3.8/site-packages/autokey/UI_common_functions.py", line 72, in checkRequirements
    missing_modules = checkModuleImports(common_modules+qt_modules)
  File "/home/elliria/.local/lib/python3.8/site-packages/autokey/UI_common_functions.py", line 34, in checkModuleImports
    spec = importlib.util.find_spec(module)
AttributeError: module 'importlib' has no attribute 'util'
```
Note that all the mentions of missing commandline programs most likely aren't relevant, because I get the same mentions when I successfully launch the GTK version of AutoKey in the same way.

**Comment by josephj11** [comment] 2021-11-20 13:28
@Elliria looks like a typo in your appended issue report. It talks about the Qt front end, but lists the GTK version as the one which is affected.

**Comment by Elliria** [comment] 2021-11-20 14:36
Whoops, and good catch, Joe. It's fixed.

**Comment by BlueDrink9** [comment] 2022-01-07 22:11
These are separate issues I think. The original post should be fixed in beta I believe. Elliria's issue is more strange, and is probably OS-specific. The version of importlib might be different.

**Comment by BlueDrink9** [comment] 2022-01-07 22:25
@Elliria what is your python version where that error occurs?

**Comment by BlueDrink9** [comment] 2022-01-07 22:32
If you edit `/home/elliria/.local/lib/python3.8/site-packages/autokey/UI_common_functions.py` and add `import importlib.util` on the second line, does that fix the issue?

**Comment by Elliria** [comment] 2022-01-08 11:10
The most recent LTS release of Kubuntu that I've been using has python3 version ```3.8.2-@ubuntu2``` in it and, yes, that fixes the issue. How nice. Now I just need to finish all the tests I've been doing on the GTK version of the beta and start over with the Qt version to see how they stack up to each other. Thanks for the help, BlueDrink9. That's perfect.

**Comment by BlueDrink9** [comment] 2022-01-08 23:02
good to know that fixes it. I will include that line in the file.

**Closed as completed** 2022-01-08 23:03 UTC
Labels: bug, autokey-qt, help-wanted, installation/configuration, beta

**Comment by Elliria** [comment] 2022-01-12 19:39
Thank you. I've left the change in my copy so I can use both of them to do my beta tests (which are taking a long time because I have a lot of phrases and scripts).
