### ISSUE TITLE
"Insert date" in Terminator introduces unexpected linefeed (LF / 0x0A).

### ISSUE THREAD

**Issue by deragon** [autokey/autokey#75] opened 2017-03-26 07:33 UTC
## Classification:

UI/Usability

## Reproducibility:

Always

## Summary

Example "Insert date" introduces unexpected linefeed (LF / 0x0A) character, but only in the [Terminator](https://gnometerminator.blogspot.ca/p/introduction.html) version  0.98-1 terminal.  

## Steps to Reproduce

1. Open a instance of [Terminator](https://gnometerminator.blogspot.ca/p/introduction.html) terminal 
2. Run the "Insert date" script

## Expected Results

Following is the expected output of running the script four times in a row, in vim running in terminal mode, under Terminator:

    Sun Mar 26 03:11:32 EDT 2017Sun Mar 26 03:11:36 EDT 2017Sun Mar 26 03:11:39 EDT 2017Sun Mar 26 03:11:48 EDT 2017

## Actual Results

Following is the actual output of running the script four times in a row, in vim running in terminal mode, under Terminator.

    Sun Mar 26 03:1
    1:32 EDT 2017Sun Mar 26 03:11
    :36 EDT 2017Sun Mar 26 03
    :11:39 EDT 2017Sun Mar 26 03:11
    :48 EDT 2017

The output in hex:

    0000000   S   u   n       M   a   r       2   6       0   3   :   1  \n
    0000010   1   :   3   2       E   D   T       2   0   1   7   S   u   n
    0000020       M   a   r       2   6       0   3   :   1   1  \n   :   3
    0000030   6       E   D   T       2   0   1   7   S   u   n       M   a
    0000040   r       2   6       0   3  \n   :   1   1   :   3   9       E
    0000050   D   T       2   0   1   7   S   u   n       M   a   r       2
    0000060   6       0   3   :   1   1  \n   :   4   8       E   D   T    
    0000070   2   0   1   7  \n                                            
    0000075

The same result is obtained if pasting directly into Terminator's bash prompt, without vim running.

## Version

AutoKey-Py3, most recent github code as of 2017-03-26 03:23:09 EDT

Distro:  Ubuntu 16.04 LTS Xenial Xerus

## Notes

Terminator version 0.98-1 does not exhibit any bug when normally pasting code into it or typing within.  It is a stable product AFAIK.  It is the only application I know that suffers of this bug.  Note sure if the bug is within Terminator or an odd interaction between Terminator and AutoKey-Py3.

gnome-terminal does not exhibit this problem.

**Comment by holstuwe** [comment] 2017-05-14 15:48
Copy that. Ubuntu 17.04 with latest autokey from github. Does not only happen in terminator, but everywhere else where "date" is used.

Examplescript:

o1 = "uh "
o2 = system.exec_command("date '+%Y-%m-%d %H:%M:%S'")
output = "("+ o1 + o2
keyboard.send_keys(output)
keyboard.send_key("<backspace>")
keyboard.send_key(")")

Last two line are my ugly workarround (I'm not a programmer) for getting the desired result.
I'm using this script only in documents, not in a terminal, therefore with this workarround the result is ok for me.

**Comment by troxor** [comment] 2017-07-26 23:02
Does this issue happen in other Java-based apps? Could be related to #92

**Comment by luziferius** [comment] 2018-05-20 14:02
Looks like #145 is a duplicate of this one. Therefore this issue should be fixed in merged PR #146, too.
@deragon @holstuwe system.exec_command() function now properly trims the last newline at end of command output. The fix ( https://github.com/autokey/autokey/pull/146) should already be uploaded to  the new PPA (and of course when using pip3 + github link).
Could you try it and verify your issue is fixed?

**Closed as completed** 2018-06-18 10:18 UTC
