### ISSUE TITLE
PPA out dated 

### ISSUE THREAD

**Issue by MasterCATZ** [autokey/autokey#112] opened 2017-12-12 15:35 UTC
Err:14 http://ppa.launchpad.net/troxor/autokey/ubuntu artful Release     
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by troxor** [comment] 2017-12-30 03:02
Dupe of #81

**Closed as completed by troxor** 2017-12-30 03:02 UTC
