### ISSUE TITLE
Crash when setting keyboard shortcut

### ISSUE THREAD

**Issue by owcz** [autokey/autokey#48] opened 2016-12-11 01:25 UTC
A handful of times, AK will crash when I'm adding a keyboard shortcut to a phrase. I click "Press to Set" on "Set Hotkey" and the screen will lock up. I'll get a notif to kill the process, and then it locks up on that too. Could use some help in diagnosing whether it's something with the OS or with AK, as I haven't had a similar crash with any other software. What kind of logs would be useful next time this happens? Running latest Manjaro 16.10.1 and kernel 4.8.9.

**Comment by troxor** [comment] 2016-12-11 05:12
Related/duplicate of #42, please provide a reliable test case and provide as much information as you can to help reproduce. Kernel version and distribution are at best vague, and at worst irrelevant, information.

**Closed as completed by troxor** 2016-12-11 05:12 UTC
