### ISSUE TITLE
Does not remove abbreviation in Bash

### ISSUE THREAD

**Issue by allstar87** [autokey/autokey#202] opened 2018-10-29 03:38 UTC
## Classification:

Bug

## Reproducibility:

Always

## Summary

Activating a script in a Bash terminal window by way of an abbreviation, it sends the abbreviation as a bash command.

## Steps to Reproduce (if applicable)

Make an autokey script, doesn't matter the contents
assign an abbreviation to it
open a bash terminal
activate autokey script by typing abbreviation and space bar.

## Expected Results

The abbreviation should disappear and then run the script.

## Actual Results

It enters the abbreviation as a command, which monkeys with script execution and timing. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please put the output into a block quote (enclose in triple backticks).
```
Example block quote.
```

## Version

AutoKey version: 

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Do not recall

Distro:

Linux Mint 18.2 Cinnamon

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

Activate script via hotkey combo instead.

**Comment by josephj11** [comment] 2018-10-29 22:31
Hi, allstar87. Open the main AutoKey window and select Help->About AutoKey. That will give you the version.

There  have been several issues around abbreviations lately - with fixes applied, so we really do need to know exactly which version you're running.

Bash runs in a terminal, it's not the terminal itself, so what terminal program are you using? There are a few such as xterm which don't play well with AutoKey.

Does your issue also occur elsewhere such as in a text editor?

I am using AutoKey 0.95.4 on kubuntu 18.04. It works fine in konsole running bash.

You may want to take a look at our [Problem Reporting Guide](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide).

If this problem hasn't already been fixed, then we'll need a trace to look into it further. The guide tells you how to do that.

**Comment by luziferius** [comment] 2019-02-12 14:15
Probably duplicate of #132.
If the receiving applications ignores key presses generated by AutoKey, there is currently no workaround to get it to work.
Well, `xterm` can be configured to work, see https://github.com/autokey/autokey/issues/132#issuecomment-392321382 for details.

There is a highly experimental workaround, but nothing that can be used in production: https://github.com/autokey/autokey/issues/195#issuecomment-428200543

**Closed as completed by luziferius** 2019-02-12 14:15 UTC
Labels: duplicate
