### ISSUE TITLE
Sent keys do not work with modifiers

### ISSUE THREAD

**Issue by Jont828** [autokey/autokey#360] opened 2020-01-27 16:58 UTC
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.9

Used GUI (Gtk, Qt, or both): GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). AUR

Linux Distribution: Arch

## Summary

I used Autokey to map Hyper+i/j/k/l to up/left/down/right arrow keys. Usually, when I press shift+left/right arrow, it will start to highlight in that direction of that arrow. However, when I press Shift+Hyper+j/l, it does not highlight any text. In fact, nothing is typed and the cursor does not move at all. This appears to be the case with custom mappings to send home and end as well.

My script contains `keyboard.send_keys('<right>')` and the keybinding is `Hyper+L`

## Steps to Reproduce (if applicable)

Create a keymapping to send an arrow or navigation key and try to use that keymapping with a modifier. 

## Expected Results

It should work as if I pressed the actual keys together and move the cursor with highlighting/expected behavior.

## Actual Results

Nothing happens

**Comment by BlueDrink9** [comment] 2020-01-27 18:47
This is a duplicate of https://github.com/autokey/autokey/issues/322

In the meanwhile, make a map for the combo you want that includes shift explicitly

**Comment by luziferius** [comment] 2020-01-28 13:07
It is kind of by design. `<hyper>+<right>` is a different hotkey than `<shift>+<hyper>+<right>`.

Let’s step back a bit and examine the world outside of AutoKey: What do you expect when you press `<shift>+<ctrl>+v` in a text editor?

Does it paste the clipboard in UPPER CASE? Because the text editor has`<ctrl>+v` assigned as "paste clipboard" and the pressed keys clearly _contain_ `<ctrl>+v`. So it should paste the clipboard. But you also hold `<shift>`, thus by the semantics of that modifier, it should paste the clipboard content as UPPER CASE.
But none of that happens in other applications, because each set of held modifiers is normally seen as distinct and can be assigned to do a specific task.

Implementing this proposal will implement the above semantics inside AutoKey. I do see the use case for this inside AutoKey, but I’m not sure if implementing something that is orthogonal to the rest of the world is a wise decision.

**Comment by BlueDrink9** [comment] 2020-01-28 20:09
Of note, autohotkey has this as an option when creating hotkeys. The `~` modifier iirc

**Comment by Jont828** [comment] 2020-01-29 19:11
Thanks for the suggestion! Adding the shift+hyper+l as an explicit remap seems to be working. 

My main intention is it to work like a 60% keyboard where the Fn layer is applied _before_ the computer's modifiers get applied. For example, in Karabiner Elements, mapping Caps Lock to a new Fn key and then using <new Fn>l -> <right> works as if it was a built in key. I see how that might not  be feasible for development, though.

On another note, I do have some conflicts with caps lock. Since caps lock is my hyper key, when I have caps lock on (through pressing double shift) and try to use <hyper>l to <right>, it does move the cursor right but also adds a capital "L". Is there any way to have Autokey ignore the fact that caps lock is on?

**Comment by BlueDrink9** [comment] 2020-01-29 23:23
Can you please edit that comment and make a new issue? (if you think it's separate)

**Comment by josephj11** [comment] 2020-01-30 17:55
@Jont828 FYI: While reassigning the `CapsLock` key works with AutoKey in some instances, there is an underlying issue (bug) within AutoKey where it treats the key as having its original function in some situations even when it has been remapped or disabled. Just something to be aware of.

**Comment by luziferius** [comment] 2020-02-04 20:39
> On another note, I do have some conflicts with caps lock. Since caps lock is my hyper key, when I have caps lock on (through pressing double shift) and try to use l to , it does move the cursor right but also adds a capital "L". Is there any way to have Autokey ignore the fact that caps lock is on?

You can try the current git master. It contains a setting to ignore and not track the status of the caps lock key.

**Comment by josephj11** [comment] 2023-04-06 17:13
I think this and #322 should probably be closed as won't fix.

**Comment by Elliria** [comment] 2023-04-06 18:37
This one for sure. Its behavior is expected and isn't an AutoKey issue. The **Shift** key in combination with any of the arrow keys is how selections are made using just the keyboard. It's an operating-system thing, so overriding it would have to be done with key-mapping to prevent the operating system from intercepting the call when it comes with those key-combinations.

**Closed as completed** 2023-04-07 11:02 UTC
Labels: duplicate, enhancement, wontfix, autokey triggers
