### ISSUE TITLE
AUtomatically start in Preferences not working

### ISSUE THREAD

**Issue by praenubilus** [autokey/autokey#178] opened 2018-08-21 16:01 UTC
## Classification:

(Pick one of: Bug, UI)

## Reproducibility:

Always

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

Open Edit->Preferences-> check "Automatically start AutoKey at login"
Then click OK

## Expected Results

- AutoKey should started automatically at login

## Actual Results

- As long as you reopen the preferences, it has already been unchecked. Also, it will not start automatically at login.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please put the output into a block quote (enclose in triple backticks).
```
Example block quote.
```

## Version

AutoKey version: 0.90.4

Used GUI (Gtk, Qt, or both): 

GTK (Ubuntu 18.04)

Installed via: PPA
Distro:

**Comment by luziferius** [comment] 2018-08-21 16:08
Duplicate of https://github.com/autokey/autokey/issues/149

The fix will be included in 0.95.3.

Manual fix: Create this directory: `~/.config/autostart`. Reason: Current versions assume it already exists and fail to create the `autostart` directory if it doesn’t exist.

**Comment by luziferius** [comment] 2018-08-21 20:02
Fix is in the just released version 0.95.3.

If it still happens, feel free to reopen the issue.

**Closed as completed by luziferius** 2018-08-21 20:02 UTC
Labels: duplicate
