### ISSUE TITLE
Phrase from selection example script throws an exception

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#665] opened 2022-02-11 22:26 UTC
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

kubuntu 18.04

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

0.96.0 Beta 10

### How did you install AutoKey?

From GitHub debs

### Can you briefly describe the issue?

Phrase from selection example script throws an exception. 

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

I modified one line of the example to put the new phrase where my phrases live.

    folder = engine.get_folder("/home/bigbird/Autokey/My Phrases")

### What should have happened?

It should have created a new phrase from my selection.

### What actually happened?

It throws an exception.

### Can you provide the output of the AutoKey command?

```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 530, in _execute
    exec(compiled_code, scope)
  File "/home/bigbird/.config/autokey/data/Sample Scripts/Phrase from selection.py", line 9, in <module>
    engine.create_phrase(folder, title, contents)
  File "/usr/lib/python3/dist-packages/autokey/scripting/engine.py", line 230, in create_phrase
    replace_existing_hotkey)
  File "/usr/lib/python3/dist-packages/autokey/scripting/engine.py", line 623, in validateArguments
    if folder.temporary and not temporary:
AttributeError: 'NoneType' object has no attribute 'temporary'
```

### Anything else?

/home/bigbird/Autokey/ is a symlink to the actual directory on my system. IDK if this makes a difference.

**Comment by BlueDrink9** [comment] 2022-04-02 01:32
Looks like an actual error on my part, thanks. Can you please post the .json for your autokey folder? (feel free to sanitise/pastebin with password and dm me the pw)

**Comment by josephj11** [comment] 2022-04-03 08:00
Hopefully, this is what you want to see.
This is the contents of ~/.config/autokey_beta/autokey.json ~/.config/autokey is a symlink to ~/.config/autokey_beta/

```
{
    "version": "0.96.0-beta.10",
    "userCodeDir": "/home/bigbird/Autokey/autokey_scripts/Modules",
    "settings": {
        "isFirstRun": false,
        "serviceRunning": true,
        "menuTakesFocus": false,
        "showTrayIcon": true,
        "sortByUsageCount": false,
        "promptToSave": false,
        "enableQT4Workaround": false,
        "interfaceType": "XRecord",
        "undoUsingBackspace": true,
        "windowDefaultSize": [
            1354,
            681
        ],
        "hPanePosition": 260,
        "columnWidths": [
            244,
            57,
            411
        ],
        "showToolbar": true,
        "notificationIcon": "autokey-status",
        "workAroundApps": ".*VirtualBox.*|krdc.Krdc",
        "triggerItemByInitial": false,
        "disabledModifiers": [],
        "scriptGlobals": {},
        "gtkTheme": "classic",
        "gtkExpandedRows": [
            "0",
            "0:3"
        ],
        "pathLastOpen": "0:3:2"
    },
    "folders": [
        "/home/bigbird/Autokey"
    ],
    "toggleServiceHotkey": {
        "enabled": false,
        "modifiers": [
            "<shift>",
            "<super>"
        ],
        "hotKey": "k"
    },
    "configHotkey": {
        "enabled": false,
        "modifiers": [
            "<super>"
        ],
        "hotKey": "k"
    }
}
```

**Comment by BlueDrink9** [comment] 2022-06-05 03:53
Hesitantly assigning this one to user error. Only way I could replicate it was by trying to get a folder that autokey doesn't know about - which means `engine.get_folder` returns None. That's expected behaviour.

However, I have added an error message when you call an engine function with a non-existent folder, which will make any user error more obvious in future.

**Closed as completed** 2022-06-05 04:41 UTC
Labels: bug, scripting, beta
