### ISSUE TITLE
"RuntimeError: release unlocked lock" when using emoji as abbreviation -> afterwards no more usage of keyboard possible

### ISSUE THREAD

**Issue by jedet** [autokey/autokey#275] opened 2019-04-27 11:34 UTC
## Classification:

Crash, Hang, Bug

## Reproducibility:

Always, but it takes time. I can reproduce it daily. It mainly happens with smileys, like 🤔

## Version

AutoKey version: 0.95.1
![image](https://user-images.githubusercontent.com/25966627/56849023-6efc1f00-68ef-11e9-82e6-25bb8c59bc92.png)

Used GUI (Gtk, Qt, or both): 
GTK

Installed via: (PPA, pip3, …).

Linux Distribution: Linux Mint 19.1 Cinnamon
Cinnamon Version: 4.0.10

## Summary

When I use different kind of autokeys, mainly the emojies, like "hmm", "hehe", etc.
![image](https://user-images.githubusercontent.com/25966627/56849053-f6499280-68ef-11e9-9998-e7080a12310f.png) the keyboard is no longer responsive. The only way to fix it is to use the "System Monitor" and kill the autokey-gtk-process.

## Steps to Reproduce (if applicable)

1. use linux mint 19
2. install autokey-gtk
3. create a new abbreviation, as shown here: ![image](https://user-images.githubusercontent.com/25966627/56849053-f6499280-68ef-11e9-9998-e7080a12310f.png) (this is the smiley used: 🤔)
4. use this abbreviation "hmm" several times or after some minutes of having autokey-gtk running it happens. Latest after about 1 hour

## Expected Results

- No crash
- Keyboard should be usable in any case and shouldn't be blocked
(Only mouse is usable in that state)

## Actual Results

```
2019-04-27 13:16:53,769 DEBUG - service - No phrase/script matched hotkey
2019-04-27 13:16:53,770 DEBUG - iomediator - Send via clipboard
2019-04-27 13:16:53,770 DEBUG - service - Input stack at end of handle_keypress: deque([], maxlen=150)
2019-04-27 13:16:53,770 DEBUG - interface - Sending string via clipboard: 🤔
2019-04-27 13:16:53,770 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 206, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
```

I guess this is the stacktrace and error-message here:
```
2019-04-27 13:16:53,770 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 206, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
```

## Notes

No workaround found. Only restarting autokey-gtk. Then it can happen that I run into the same issue again after some minutes.

**Comment by luziferius** [comment] 2019-04-29 08:44
That stack trace, even if it happens in this situation, is not the cause. I can totally see, why you guessed it, though. This locking error is almost harmless. Somewhere in the code a mutex is more often released than aquired. This is a known issue and you’ll see this in the latest version, too.

The issue you are experiencing is caused by a bug in the clipboard pasting code, resulting in AutoKey not releasing a grabbed keyboard. See #72, #226.
It is fixed in the latest version (0.95.7). You have 0.95.1, so you probably installed from the sporkwitch PPA, whose maintainer unfortunately vanished. The easiest way to get this fixed is to install the newest version manually. [Link to the GitHub release page.](https://github.com/autokey/autokey/releases/tag/v0.95.7)

Either (choose one)

- install the debian packages (both `autokey-common` and `autokey-gtk`) built by me, that are attached to the GitHub release. (Same disclaimer, as with any PPA: Use at your own risk. If you trust me that I didn’t include something fishy, use the packages.)
- or [build the debian packages yourself](https://github.com/autokey/autokey/wiki/Packaging#building-debian-packages-locally). You can grab the Source code archive attached to the release (those are automatically generated by GitHub) or just use git to check out the repository. Follow the linked instructions to generate your own Debian packages and install those.
- or uninstall the current version and do a `pip3` install (not recommended on Ubuntu, because we have working packages for it)

**Closed as completed** 2019-04-29 12:57 UTC
Labels: bug, duplicate
