### ISSUE TITLE
Is there a way to initiate script execution with mouse click rather than key press?

### ISSUE THREAD

**Issue by SN-CH** [autokey/autokey#937] opened 2024-03-04 12:16 UTC
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Unknown

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [X] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [X] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Lubuntu 20.04.

### Which AutoKey GUI did you use?

None

### Which AutoKey version did you use?

0.96.0. GTK.

### Can you briefly describe the issue?

Frankly, I am not sure if the following is a bug, but I do not see any logical rationale not to provide the described functionality (of course, there may be rather serious technical reasons). So, I wonder if this was inadvertently omitted.

The listener behind the «Set hotkey» dialogue fails at registering mouse click events. Is there any way to bypass this? For example, to edit the corresponding json-file (I tried but my attempts to find proper syntax to make it work were futile)?

### Can the issue be reproduced?

Always

**Comment by josephj11** [comment] 2024-03-05 15:58
@SN-CH Welcome to the AutoKey community!

This request is a duplicate of #519. That issue details a few partial workarounds for this.

Unless you feel that this request is unique in some way, it should be closed.

FYI: AFAIK, we have no active developers ATM. If you know anyone who might be interested, please send them our way! (There are still one or two OG developers who might be available to answer questions... so they wouldn't have to start with no support.)

**Comment by SN-CH** [comment] 2024-03-05 16:25
@josephj11 Thank you for your reply! I shall need to ponder over what is written in the thread you are referring to. Anyway, this is exactly the same problem. That makes the ticket to be a perfect duplicate. I shall close it as such.

As for your request, I happen to know a few senior Python developers. While I have no idea how busy those people are in the meantime, I trust it won't do any harm to ask. If some one of them comes interested, I shall refer him to you (I really like this well-thought-out and useful piece of software and it would be a shame to see it turning into an abandonware, so yes, I shall ask).

**Comment by SN-CH** [comment] 2024-03-05 16:26
Closed as a duplicate of https://github.com/autokey/autokey/issues/519.

**Closed as not planned** 2024-03-05 16:25 UTC
Labels: duplicate, enhancement, autokey triggers

**Comment by josephj11** [comment] 2024-03-05 19:41
@SN-CH Thank you! If any of them want to just dabble at first, also refer them to [Codetriage](https://www.codetriage.com/autokey/autokey).

**Comment by SN-CH** [comment] 2024-04-12 08:11
@josephj11 I reached out to four senior Python developers I know. Unfortunately, three of them are too busy nowadays to make this kind of commitment and the last one has some rather serious health issues, so he declined as well. Sorry it did not work. I sincerely hope you'll be able to find someone to keep this good project afloat.

**Comment by josephj11** [comment] 2024-04-12 15:23
Good people tend to be busy. Thanks for trying!
