### ISSUE TITLE
AutoKey don't run under Ubuntu 16.04 -> Xlib.error.BadAccess

### ISSUE THREAD

**Issue by MultiStorm** [autokey/autokey#68] opened 2017-02-02 12:42 UTC
Hello,
i have try to install autokey-py3 on my Ubuntu 16.04 lts

first installation with Git and setup.py failt maybe a python version Problem

then i add the PPA and install over there but now, when i start over the UI shortcut i see the Icon in the  startet for 10 - 15 sec an the icon remote from the starter, when i start over terminal i see this Errors:

:~$ autokey
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 247, sequence_number = 15, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 247, sequence_number = 16, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 247, sequence_number = 17, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 247, sequence_number = 18, major_opcode = 33, minor_opcode = 0

what can i do?

**Comment by troxor** [comment] 2017-02-02 17:21
Duplicate of #67

**Closed as completed by troxor** 2017-02-02 17:21 UTC
