### ISSUE TITLE
Autokey does not allow recording of hotkeys (using qt does not fix it)

### ISSUE THREAD

**Issue by CometVoid** [autokey/autokey#764] opened 2023-01-31 07:33 UTC
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

ima just paste neofetch out of lazyness and to be thourough

OS: Arch Linux x86_64 
Host: MS-7D14 1.0 
Kernel: 6.1.8-arch1-1 
Uptime: 1 hour, 59 mins 
Packages: 1404 (pacman), 5 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Plasma 5.26.5 
WM: kwin 
WM Theme: Breeze 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: yakuake 
CPU: AMD Ryzen 5 5600G with Radeon Graphics (12) @ 3.900GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M 
Memory: 3781MiB / 13870MiB 

                                                                 
                                                                 
`

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

0.96.0-4

### How did you install AutoKey?

AUR (using yay)

### Can you briefly describe the issue?

Autokey does not record keystrokes when making a hotkey

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. attempt to set a keybind

### What should have happened?

keypresses should have been recorded after I pressed record

### What actually happened?

Nothing, occaisonally a freeze.

### Do you have screenshots?

![Screenshot_20230130_232202](https://user-images.githubusercontent.com/80859724/215693266-debf5de2-e614-4b1c-858b-446713aa5757.png)

(I'm spamming the keyboard but you can't tell because it's a screenshot)

### Can you provide the output of the AutoKey command?

```bash
This is both the autokey-gtk and autokey-qt output

[comet@kyber ~]$ autokey-gtk
2023-01-30 23:17:53,157 INFO - autokey.gtkapp - Initialising application
2023-01-30 23:17:53,160 INFO - autokey.gtkapp - Initialise global hotkeys
2023-01-30 23:17:53,160 INFO - autokey.configmanager.configmanager - Loading config from existing file: /home/comet/.config/autokey/autokey.json
2023-01-30 23:17:53,160 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0
2023-01-30 23:17:53,162 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2023-01-30 23:17:53,163 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2023-01-30 23:17:53,163 INFO - autokey.service - Starting service
2023-01-30 23:17:53,187 INFO - autokey.iomediator.iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2023-01-30 23:17:53,191 INFO - autokey.interface - XRecord interface thread starting
2023-01-30 23:17:53,191 INFO - autokey.service - Service now marked as running
2023-01-30 23:17:53,208 INFO - autokey.gtkapp - Entering main()
2023-01-30 23:17:59,859 INFO - autokey.gtkapp - Displaying configuration window
2023-01-30 23:18:16,791 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2023-01-30 23:18:16,792 INFO - autokey.configmanager.configmanager - Persisting configuration
2023-01-30 23:18:16,792 INFO - autokey.configmanager.configmanager - Backing up existing config file
2023-01-30 23:18:16,793 INFO - autokey.configmanager.configmanager - Finished persisting configuration - no errors
2023-01-30 23:18:21,294 INFO - autokey.gtkapp - Shutting down
2023-01-30 23:18:21,294 INFO - autokey.service - Service shutting down
2023-01-30 23:18:22,216 INFO - autokey.configmanager.configmanager - Persisting configuration
2023-01-30 23:18:22,216 INFO - autokey.configmanager.configmanager - Backing up existing config file
2023-01-30 23:18:22,217 INFO - autokey.configmanager.configmanager - Finished persisting configuration - no errors
2023-01-30 23:18:23,218 INFO - autokey.monitor - Shutting down file monitor
[comet@kyber ~]$ autokey-qt
2023-01-30 23:21:25,204 INFO - autokey.qtapp - Initialising application
2023-01-30 23:21:25,213 INFO - autokey.qtapp - Initialise global hotkeys
2023-01-30 23:21:25,213 INFO - autokey.configmanager.configmanager - Loading config from existing file: /home/comet/.config/autokey/autokey.json
2023-01-30 23:21:25,213 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.96.0
2023-01-30 23:21:25,215 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2023-01-30 23:21:25,215 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2023-01-30 23:21:25,215 INFO - autokey.service - Starting service
2023-01-30 23:21:25,240 INFO - autokey.iomediator.iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2023-01-30 23:21:25,244 INFO - autokey.interface - XRecord interface thread starting
2023-01-30 23:21:25,244 INFO - autokey.service - Service now marked as running
2023-01-30 23:21:25,246 INFO - autokey.qtui.notifier - Creating static context menu actions.
2023-01-30 23:21:25,247 INFO - autokey.qtui.notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2023-01-30 23:21:25,249 INFO - autokey.qtui.notifier - System tray icon notifier created.
2023-01-30 23:21:29,784 INFO - autokey.qtapp - Displaying configuration window
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2023-01-30 23:21:56,470 INFO - autokey.qtapp - Displaying configuration window
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2023-01-30 23:22:24,180 INFO - autokey.qtapp - Displaying configuration window
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
2023-01-30 23:22:28,824 INFO - autokey.qtapp - Shutting down
2023-01-30 23:22:28,825 INFO - autokey.service - Service shutting down
2023-01-30 23:22:30,306 INFO - autokey.configmanager.configmanager - Persisting configuration
2023-01-30 23:22:30,306 INFO - autokey.configmanager.configmanager - Backing up existing config file
2023-01-30 23:22:30,307 INFO - autokey.configmanager.configmanager - Finished persisting configuration - no errors
2023-01-30 23:22:31,308 INFO - autokey.monitor - Shutting down file monitor
[comet@kyber ~]$
```

### Anything else?

I found a workaround.

Editing the .json file for the script manually works, and autokey will detect the hotkeys and activate scripts. for anyone else with this issue who might not know the format for setting hotkeys via the json it's    

    "hotkey": {
        "modifiers": ["<ctrl>"],
        "hotKey": "q"
        },

EDIT: this may be a wayland issue, even though I have xorg-xwayland installed and running and there seems to be no other issues than this so far. Haven't used the program for long though, i just wanted to make a hotkey that spams voicelines and kicks barrels really hard in deeprock

**Comment by CometVoid** [comment] 2023-01-31 07:33
wow I miss-spelt thorough. amazing

**Comment by josephj11** [comment] 2023-01-31 09:49
Welcome to the AutoKey community, Cometvoid!

I just rescanned the trace and it contains that dirty 7 letter word, "Wayland".

When you log in to your system, there should be a choice to run Xorg/X11 instead of Wayland. If you select that, everything should work much better. The Wayland X11 compatibility magic doesn't fix this.

I probably should delete the rest of this post, but I'll leave it here for now as a reminder to me to read  traces more carefully!

It looks like you're running AutoKey under Xorg/X11 (as you should be), but I have to ask because AutoKey isn't compatible with Wayland.

Let me restate your problem to make sure I understand it.

You are running the latest version of AutoKey under X11.
When you are able to trigger your script, it works correctly.
When you attempt to set a hotkey for your script using either GUI front end, something goes wrong.

This is  where it gets weird.

In your screen shot, the Record a key combination button appears to be disabled (this could be  because you already pressed it). However, both the Ctrl and Alt indicators/buttons appear selected (as would happen if you were pressing them as part of the desired hotkey). But the dialog shows that no normal key press has been detected because it still says Key: (None).

This is weird because when I do this, that message is replaced by "Press a key or combination..." and the Ctrl button is selected by default. Your screen shot shows Alt also being selected, but the message hasn't changed to indicate that you are in the process of selecting the hotkey combination.

So it looks both like you're selecting a hotkey and like you're not selecting a hotkey. Clearly not good.

Since the traces don't appear to show anything interesting, this has got me stumped.

Do any other system or Python messages appear on your terminal when testing this?

Is AutoKey newly installed on this system or was it previously working until something else changed?

I have never seen this problem before. It's particularly weird because we have a number of Arch/Arch derivative users and no one else has reported anything like this so far.

I think we will have to wait for a developer to look at this. That might take a while because our current developer has been inactive for several weeks and I don't know when he will be back. I will make a request on [Gitter](https://gitter.im/autokey/autokey) for our other Arch users to take a look at this to see if they have any ideas.

**Comment by Elliria** [comment] 2023-01-31 21:25
Don't the ```qt.qpa.wayland: Wayland does not support QWindow::requestActivate()``` lines in the trace mean that **Wayland** is being used instead of **Xorg**? If so, have you tried using a **Xorg** session instead of **Wayland**, @CometVoid?

**Comment by josephj11** [comment] 2023-02-01 09:01
@Elliria I edited my last post very shortly after posting it when I took another look at the traces and the report and saw Wayland references.

**Comment by Elliria** [comment] 2023-02-02 19:19
Ah, okay. I wanted to make sure I understood it, too, because that was new to me. It's a shame that GTK doesn't also give us such an easy way to see that Wayland is in use. Was that Qt error message written into the AutoKey code or is that standard Qt behavior?

**Comment by josephj11** [comment] 2023-02-03 18:29
Looks like AutoKey tried to activate the window using a Qt API call and Qt got upset because it doesn't work in Wayland.

If you wanted to be sure (or are looking for something else in the future),  you could go into your AutoKey source code (which you have a copy of on your computer) and go into the lib directory and do a few recursive greps for anything that looks like that message. That's how I find things when I don't know where to look.

If you do find anything interesting, grep also has a couple of options that let you print a few lines before and/or after each match it finds to give you some context to narrow down which results to explore further. It can also print the file name and line number of each match.

If you want assistance with grep or other CLI fu, let me know.

**Comment by Elliria** [comment] 2023-02-04 13:49
I had to poke around a bit to find it, but it seems to be in the ```/usr/lib/python3/dist-packages/autokey/``` directory. Thanks for the tip. I'll grep around in there from time to time.

**Comment by MattiJarvinen** [comment] 2023-10-22 13:50
Just bumped into the same issue with Raspberry PI OS, Bookworm 64bit autokey-gtk_0.96.0_all.deb Wayland is default.

Might be easier to add arrow keys by changing the keyboard now or just remapping a new layout.

**Comment by josephj11** [comment] 2023-10-24 06:30
@MattiJarvinen As you have experienced, some things work in Wayland, but nothing is guaranteed. There should be a way to select X11 as your display manager when you login. (The Wayland X11 compatibility add-on doesn't do enough for AutoKey.)

If you have a compelling need to use Wayland, we have an experimental branch that works with it, but it's not feature complete. One thing I believe is missing is window filters. If you want to try that, come over to [Gitter](https://gitter.im/autokey/autokey) and we'll see if we can get you setup.

**Comment by josephj11** [comment] 2023-10-24 06:58
Since this appears to have been caused by running under Wayland instead of on X11 as required, this issue should be closed as invalid.

**Closed as completed** 2023-10-28 13:51 UTC
Labels: autokey triggers, invalid, installation/configuration
