### ISSUE TITLE
display of error messages

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#357] opened 2020-01-22 03:37 UTC
##
Enhancement
Reproducibility:  Sometimes
Version: GTK
AutoKey version: 95.8 GTK
Used GUI (Gtk, Qt, or both): GTK
Linux Distribution: Linux Mint 19.3

Notes: Some error messages are directly accessible from the panel icon, and some only when the main window is opened, and found under Menu/Tools. Would it be possible to access all from the panel icon?

**Comment by luziferius** [comment] 2020-01-25 23:32
There _should_ be no difference...

Is the behaviour totally random or is there a certain kind of error that is always accessible and one kind that is never accessible? That would help narrowing down the issue.

Do you have an example of an error that is not accessible from the panel?

**Comment by ineuw** [comment] 2020-01-29 15:29
Apologize for the delay in replying. I have no results yet, but I have to test 80+ scripts to find the one with the error is not viewable the panel icon menu. It's a slow process, so please keep this open for the time being.

**Comment by luziferius** [comment] 2020-02-11 23:44
No problem, we currently have no time limit policy that force-closes issues on inactivity.

**Comment by josephj11** [comment] 2020-02-23 09:09
@luziferius  and @ineuw When issues are closed, it would be nice to have a reason such as resolved, wontfix, could not reproduce, changed my mind, ... ;) because "closed" doesn't mean fixed. This would just be my preference.

**Comment by ineuw** [comment] 2020-02-23 18:51
josephj11, you are right. I closed the issue because I was unable to reproduce it, and with the latest version I don't expect any issues.

**Comment by ineuw** [comment] 2020-03-15 15:01
I found how this happens and how I recreated it.
1. Create a simple script with send_keys sending an undeclared variable which triggers an error accessible on the context menu of the panel.
2. Clear said error and repeat the send_keys with the same error. 
3. The error message is not displayed on the panel context menu the 2nd time.
![200315_missing_autokey_error_message](https://user-images.githubusercontent.com/10367016/76703981-40746780-66ac-11ea-93d6-d3044a2d9f77.jpg)

**Comment by luziferius** [comment] 2020-03-15 15:24
Weird.

My test script:
![AK_357_1](https://user-images.githubusercontent.com/2143820/76704362-bf7f9500-66d8-11ea-80cd-d6fd841fa2d7.png)

I tried:

- Triggered the hotkey
- Right click on the tray icon
- Click "View script error"
- Close the message box and main window
- Triggered the hotkey a second time
- Right click on the tray icon
- Click "View script error", which is available and works.

Then I tried:

- Triggered the hotkey
- Right click on the tray icon
- Click "View script error"
- Close the message box, but leave the main window open
- Triggered the hotkey a second time
- Right click on the tray icon
- Click "View script error", which is available and works.


In all cases, I get this:
![AK_357_2](https://user-images.githubusercontent.com/2143820/76704453-6bc17b80-66d9-11ea-82fe-1d55adc6e393.png)

**Comment by ineuw** [comment] 2020-03-15 16:06
It is weird, It's not an important issue and I am sure that the mystery will be resolved. This is not a new issue for me. It is like this for years, ever since the context menu error link was introduced. 
Since this is a recent Linux Mint installation, it's also possible that I set up things in a way that causes this. 
Also, I often have the main window open and minimized for quick access and modification. Posted this just to show that it's not a fairy tale. :-)

**Closed as completed** 2023-01-07 05:06 UTC
Labels: user interface
