### ISSUE TITLE
Issue with Wine + Pokemon Insurgence & Pokemon infinite fusion

### ISSUE THREAD

**Issue by Linuxplayerdesu** [autokey/autokey#384] opened 2020-03-10 15:17 UTC
autokey works well but not on thoses two games that i run with wine

>What i did

Enter script code
keyboard.send_key('f')
import subprocess #i've made a script with Xdotool doing the same as the previous line     
subprocess.call("./Xool.sh", shell=True)

>what i expect to do
1) pressing f which is the action key
2) executing my bash script in subprocess

>What happens
1) "a script has encounter a problem", and nothing else
2) When i execute the script python without autokey it didn't work for the autokey part but for the subprocess part with Xdotool it works good

>what i get in the console

 ~ $ autokey-gtk -l
/usr/lib/python2.7/dist-packages/autokey/gtkapp.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, GLib
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:19: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, Notify
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
/usr/lib/python2.7/dist-packages/autokey/gtkui/configwindow.py:20: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Pango, GtkSource, Gdk, Gio
2020-03-06 14:43:14,492 INFO - root - Initialising application
2020-03-06 14:43:14,497 INFO - root - Initialise global hotkeys
2020-03-06 14:43:14,497 INFO - config-manager - Loading config from existing file: /home/linuxplayerdesu/.config/autokey/autokey.json
2020-03-06 14:43:14,497 DEBUG - config-manager - Loading folder at '/home/linuxplayerdesu/.config/autokey/data/Sample Scripts'
2020-03-06 14:43:14,505 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2020-03-06 14:43:14,505 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/.config/autokey/data/Sample Scripts
2020-03-06 14:43:14,505 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey
2020-03-06 14:43:14,505 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/test
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/__pycache__
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/gtkui
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/gtkui/__pycache__
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/gtkui/data
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/dialogs
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/__pycache__
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/data
2020-03-06 14:43:14,506 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/settings
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/resources
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/qtui/resources/ui
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/iomediator
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/lib/autokey/iomediator/__pycache__
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/config
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/config/ubuntu-mono-dark
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/config/ubuntu-mono-light
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/config/Humanity
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/Autokey 1rst
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/debian
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/debian/source
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/doc
2020-03-06 14:43:14,507 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/doc/scripting
2020-03-06 14:43:14,508 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/Programation/Autokey/doc/man
2020-03-06 14:43:14,508 INFO - config-manager - Successfully loaded configuration
2020-03-06 14:43:14,508 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/.config/autokey/data
2020-03-06 14:43:14,508 DEBUG - inotify - Adding watch for /home/linuxplayerdesu/.config/autokey
2020-03-06 14:43:14,508 DEBUG - config-manager - Global settings: {'showTrayIcon': True, 'sortByUsageCount': True, 'scriptGlobals': {}, 'undoUsingBackspace': True, 'notificationIcon': u'autokey-status', 'enableQT4Workaround': False, 'promptToSave': False, 'menuTakesFocus': False, 'interfaceType': u'XRecord', 'windowDefaultSize': [1920, 1029], 'showToolbar': True, 'serviceRunning': True, 'columnWidths': [150, 50, 100], 'workAroundApps': u'.*VirtualBox.*|krdc.Krdc', 'hPanePosition': 480, 'isFirstRun': True}
2020-03-06 14:43:14,508 INFO - service - Starting service
2020-03-06 14:43:14,522 DEBUG - interface - Enabling sending using Alt-Grid
2020-03-06 14:43:14,523 DEBUG - interface - Modifier masks: {'<capslock>': 2, '<meta>': 8, '<alt_gr>': 128, '<numlock>': 16, '<hyper>': 64, '<ctrl>': 4, '<shift>': 1, '<alt>': 8, '<super>': 64}
2020-03-06 14:43:14,542 DEBUG - interface - Alt-Grid: XK_ISO_Level3_Shift, 65027
2020-03-06 14:43:14,542 DEBUG - interface - [(92, 0), (108, 0), (92, 2), (108, 2)]
2020-03-06 14:43:14,542 DEBUG - interface - X Server Keymap
2020-03-06 14:43:14,542 DEBUG - interface - [\] : [(17, 4), (17, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [|] : [(15, 4), (94, 4), (15, 6), (94, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [`] : [(16, 4), (16, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [1] : [(10, 1), (10, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [2] : [(11, 1), (11, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [3] : [(12, 1), (12, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [4] : [(13, 1), (13, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [5] : [(14, 1), (14, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [6] : [(15, 1), (15, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [7] : [(16, 1), (16, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [8] : [(17, 1), (17, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [9] : [(18, 1), (18, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [0] : [(19, 1), (19, 3)]
2020-03-06 14:43:14,542 DEBUG - interface - [-] : [(15, 0), (15, 2)]
2020-03-06 14:43:14,542 DEBUG - interface - [=] : [(21, 0), (21, 2)]
2020-03-06 14:43:14,542 DEBUG - interface - [~] : [(11, 4), (11, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [!] : [(61, 0), (61, 2)]
2020-03-06 14:43:14,542 DEBUG - interface - [@] : [(19, 4), (19, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [#] : [(12, 4), (12, 6)]
2020-03-06 14:43:14,542 DEBUG - interface - [$] : [(35, 0), (35, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [%] : [(48, 1), (48, 3)]
2020-03-06 14:43:14,543 DEBUG - interface - [^] : [(18, 4), (18, 6)]
2020-03-06 14:43:14,543 DEBUG - interface - [&] : [(10, 0), (10, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [*] : [(51, 0), (51, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [(] : [(14, 0), (187, 0), (14, 2), (187, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [)] : [(20, 0), (188, 0), (20, 2), (188, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [q] : [(38, 0), (38, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [w] : [(52, 0), (52, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [e] : [(26, 0), (26, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [r] : [(27, 0), (27, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [t] : [(28, 0), (28, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [y] : [(29, 0), (29, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [u] : [(30, 0), (30, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [i] : [(31, 0), (31, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [o] : [(32, 0), (32, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [p] : [(33, 0), (33, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [[] : [(14, 4), (14, 6)]
2020-03-06 14:43:14,543 DEBUG - interface - []] : [(20, 4), (20, 6)]
2020-03-06 14:43:14,543 DEBUG - interface - [a] : [(24, 0), (24, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [s] : [(39, 0), (39, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [d] : [(40, 0), (40, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [f] : [(41, 0), (41, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [g] : [(42, 0), (42, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [h] : [(43, 0), (43, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [j] : [(44, 0), (44, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [k] : [(45, 0), (45, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [l] : [(46, 0), (46, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [;] : [(59, 0), (59, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - ['] : [(13, 0), (13, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [z] : [(25, 0), (25, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [x] : [(53, 0), (53, 2)]
2020-03-06 14:43:14,543 DEBUG - interface - [c] : [(54, 0), (54, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [v] : [(55, 0), (55, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [b] : [(56, 0), (56, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [n] : [(57, 0), (57, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [m] : [(47, 0), (47, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [,] : [(58, 0), (58, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [.] : [(59, 1), (59, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [/] : [(60, 1), (60, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [Q] : [(38, 1), (38, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [W] : [(52, 1), (52, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [E] : [(26, 1), (26, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [R] : [(27, 1), (27, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [T] : [(28, 1), (28, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [Y] : [(29, 1), (29, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [U] : [(30, 1), (30, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [I] : [(31, 1), (31, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [O] : [(32, 1), (32, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [P] : [(33, 1), (33, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [{] : [(13, 4), (13, 6)]
2020-03-06 14:43:14,544 DEBUG - interface - [}] : [(21, 4), (21, 6)]
2020-03-06 14:43:14,544 DEBUG - interface - [A] : [(24, 1), (24, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [S] : [(39, 1), (39, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [D] : [(40, 1), (40, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [F] : [(41, 1), (41, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [G] : [(42, 1), (42, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [H] : [(43, 1), (43, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [J] : [(44, 1), (44, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [K] : [(45, 1), (45, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [L] : [(46, 1), (46, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [:] : [(60, 0), (60, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - ["] : [(12, 0), (12, 2)]
2020-03-06 14:43:14,544 DEBUG - interface - [Z] : [(25, 1), (25, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [X] : [(53, 1), (53, 3)]
2020-03-06 14:43:14,544 DEBUG - interface - [C] : [(54, 1), (54, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [V] : [(55, 1), (55, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [B] : [(56, 1), (56, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [N] : [(57, 1), (57, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [M] : [(47, 1), (47, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [<] : [(94, 0), (94, 2)]
2020-03-06 14:43:14,545 DEBUG - interface - [>] : [(94, 1), (94, 3)]
2020-03-06 14:43:14,545 DEBUG - interface - [?] : [(58, 1), (58, 3)]
2020-03-06 14:43:14,545 DEBUG - iomediator - Set modifier <capslock> to False
2020-03-06 14:43:14,545 DEBUG - iomediator - Set modifier <numlock> to True
2020-03-06 14:43:14,546 DEBUG - interface - Grabbing hotkey: [u'<super>'] u'k'
2020-03-06 14:43:14,546 DEBUG - interface - Grabbing hotkey: [u'<shift>', u'<super>'] u'k'
2020-03-06 14:43:14,552 INFO - interface - XRecord interface thread starting
2020-03-06 14:43:14,552 INFO - service - Service now marked as running
2020-03-06 14:43:14,583 DEBUG - phrase-menu - Sorting phrase menu by usage count
2020-03-06 14:43:14,586 INFO - root - Entering main()
2020-03-06 14:43:14,629 DEBUG - interface - Grabbing hotkey: [] u'<np_subtract>'
2020-03-06 14:43:19,580 DEBUG - service - Received mouse click - resetting buffer
2020-03-06 14:43:21,782 DEBUG - service - Received mouse click - resetting buffer
2020-03-06 14:43:24,650 DEBUG - service - Raw key: '<np_subtract>', modifiers: [], Key: -
2020-03-06 14:43:24,650 DEBUG - service - Window visible title: u'Pok\xe9mon Infinite Fusion', Window class: u'game.exe.Wine'
2020-03-06 14:43:24,650 INFO - service - Matched hotkey phrase/script with prompt=False
2020-03-06 14:43:24,651 DEBUG - service - Script runner executing: Script('pokemon')
2020-03-06 14:43:24,651 DEBUG - service - Input stack at end of handle_keypress: ['-']
2020-03-06 14:43:24,652 DEBUG - interface - Send special key: [u'f']
2020-03-06 14:43:24,652 DEBUG - service - Ignored locking error in handle_keypress
/bin/sh: 1: ./Xool.sh: not found

>my OS/version:

OS: Peppermint 10 Ten x86_64
DE: LXDE 
DM: lightdm

>Notes:

i've tried to do with a key_down, sleep and key_up then but it didn't work either
Both of theses games have the same engine (RPG maker)

**Comment by luziferius** [comment] 2020-03-10 22:20
Quick note: look at the last line of your quoted log output.
The shell invoked by your subprocess call can't find the script.

So either try to remove the relative path `./` and rely on resolving the executable location via the $PATH or provide the full path to that script.

**Comment by josephj11** [comment] 2020-03-11 02:38
A little more clarification:
We get used to knowing what the current directory is when running things in a terminal, but when we run things from a GUI, we can't assume what that directory will be, so we need to either specify a full path (which always works) or no path and let the system find it using $PATH as luziferius suggests. The problem with relying on PATH is that it may also not be what you expect. In KDE (last I checked), $HOME/bin is not included in PATH (when calling things from the GUI) which breaks all sorts of things that you would expect to work.

Your attempted workaround:

Even though it wouldn't have solved this particular issue, it has some problems of its own that are worth noting for the future:

Don't use keyboard.send_key() unless you specifically need one of its features like the repeat count. Use keyboard.send_keys() instead.

I have never seen anybody do anything successful using the press and release key API functions. I forget what the exact issue is, but it has something to do with keyboard.send_key() and/or keyboard.send_keys() unconditionally clearing things up when they exit which releases any "pressed" keys (often when the user does not want that to occur.)

**Comment by Linuxplayerdesu** [comment] 2020-03-18 17:22
Thanks, for your help but
The full path does not work saddly, it work when i use it on my shell but not with autokey.

And thanks for the advice, when i was using autohotkey on windows press & release key API was useful sometimes.

**Comment by josephj11** [comment] 2020-03-20 06:10
I'd like to see the tail of the trace when using the full path to your executable. It looks like something is wrong here, but we can't fix it on our end or on your end until we can identify the exact problem and find a way to reproduce it. Can you provide a test case we can run - preferably with as few moving parts as possible?

**Comment by Linuxplayerdesu** [comment] 2020-03-20 18:26
```
2020-03-20 19:16:07,072 DEBUG - service - Window visible title: u'Pokemon Reborn', Window class: u'game.exe.Wine'
2020-03-20 19:16:07,073 INFO - service - Matched hotkey phrase/script with prompt=False
2020-03-20 19:16:07,073 DEBUG - service - Script runner executing: Script('Subcall')
2020-03-20 19:16:07,073 DEBUG - service - Input stack at end of handle_keypress: [u'a']
2020-03-20 19:16:07,073 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 454, in execute
    exec script.code in scope
  File "<string>", line 3
    subprocess.call("/home/Linuxplayerdesu/Programation/Romhack/Macros/Xool.sh", shell=True)500ffffffffffffffffff
                                                                                       ^
SyntaxError: invalid syntax
2020-03-20 19:16:07,073 DEBUG - service - Ignored locking error in handle_keypress
2020-03-20 19:16:29,685 DEBUG - service - Received mouse click - resetting buffer
2020-03-20 19:16:29,865 DEBUG - iomediator - <ctrl> pressed

```

Okay so i got this error message now, is it meaningfull?

My actual autokey code

```
import subprocess     
subprocess.call("/home/hadoclat/Programation/Romhack/Macros/Xool.sh", shell=True)500ffffffffffffffffff

```

Btw i didn't show my bash script either i should
```
#!/bin/bash
PID=`xdotool search -n Pokemon`
xdotool windowactivate --sync $PID
xdotool type --window $PID f
```

**Comment by luziferius** [comment] 2020-03-21 10:38
@Linuxplayerdesu Why is there `500ffffffffffffffffff` at the end of the subprocess call line? :-)
Python says its a SyntaxError

**Comment by Linuxplayerdesu** [comment] 2020-03-21 17:35
Okay, now things works, how could i've been such a idiot.
i'm sorry i don't know how, and why i didn't see it

**Closed as completed** 2020-03-21 17:35 UTC

**Comment by luziferius** [comment] 2020-03-21 17:45
No problem. Such mistakes happen :)
